# Generated by Django 5.2.4 on 2025-07-14 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evento', '0010_remove_pagamento_inscricao_alter_evento_localidade_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInsc', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelado', 'Cancelado')], default='pendente')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='evento.categoria')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='evento.evento')),
                ('kit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='evento.kit')),
                ('participante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='usuarios.participante')),
            ],
        ),
        migrations.CreateModel(
            name='pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('metodoPagamento', models.CharField(choices=[('pix', 'Pix'), ('boleto', 'Boleto'), ('cartao', 'Cartão')], max_length=20)),
                ('dataPagamento', models.DateField(auto_now=True)),
                ('inscricao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='inscricoes.inscricao')),
            ],
        ),
    ]
