# Generated by Django 5.2.4 on 2025-07-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
