# Generated by Django 5.2.4 on 2025-07-10 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0003_localidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='uf',
        ),
        migrations.AddField(
            model_name='evento',
            name='localidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='evento.localidade'),
        ),
        migrations.AddField(
            model_name='participante',
            name='bairro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='localidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='evento.localidade'),
        ),
        migrations.AddField(
            model_name='participante',
            name='numero',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='rua',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='quantInscAtual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='localidade',
            name='uf',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='organizador',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='endereco',
        ),
    ]
