# Generated by Django 5.2.4 on 2025-07-10 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0004_remove_participante_endereco_remove_evento_cidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=20)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=10)),
                ('idadeMin', models.IntegerField(default=0)),
                ('idadeMax', models.IntegerField(default=0)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='evento.evento')),
            ],
        ),
        migrations.CreateModel(
            name='kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=60, null=True)),
                ('precoExtra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kits', to='evento.evento')),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=30, null=True)),
                ('tamanho', models.CharField(blank=True, choices=[('pp', 'PP'), ('p', 'P'), ('m', 'M'), ('g', 'G'), ('gg', 'GG')], null=True)),
                ('kit', models.ManyToManyField(to='evento.kit')),
            ],
        ),
        migrations.CreateModel(
            name='inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInsc', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelado', 'Cancelado')], default='Pendente')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='evento.categoria')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='evento.evento')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='evento.participante')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit', to='evento.kit')),
            ],
        ),
        migrations.CreateModel(
            name='pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='Pendente', max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('metodoPagamento', models.CharField(choices=[('pix', 'Pix'), ('boleto', 'Boleto'), ('cartao', 'Cartão')], max_length=20)),
                ('dataPagamento', models.DateField(auto_now=True)),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='evento.inscricao')),
            ],
        ),
    ]
