# Generated by Django 5.2.4 on 2025-07-10 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0005_categoria_kit_item_inscricao_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='item',
            name='kit',
        ),
        migrations.RemoveField(
            model_name='kit',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='kit',
        ),
        migrations.DeleteModel(
            name='categoria',
        ),
        migrations.DeleteModel(
            name='item',
        ),
        migrations.DeleteModel(
            name='kit',
        ),
    ]
