# Generated by Django 5.2.4 on 2025-07-10 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0006_remove_inscricao_categoria_remove_item_kit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='participante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='evento.participante'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelado', 'Cancelado')], default='pendente'),
        ),
        migrations.AlterField(
            model_name='organizador',
            name='participante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizadores', to='evento.participante'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='inscricao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='evento.inscricao'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=10),
        ),
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=20)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=10)),
                ('idadeMin', models.IntegerField(default=0)),
                ('idadeMax', models.IntegerField(default=0)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='evento.evento')),
            ],
        ),
        migrations.AddField(
            model_name='inscricao',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='evento.categoria'),
        ),
        migrations.CreateModel(
            name='kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=60, null=True)),
                ('precoExtra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kits', to='evento.evento')),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=30, null=True)),
                ('tamanho', models.CharField(blank=True, choices=[('pp', 'PP'), ('p', 'P'), ('m', 'M'), ('g', 'G'), ('gg', 'GG')], max_length=2, null=True)),
                ('kit', models.ManyToManyField(related_name='itens', to='evento.kit')),
            ],
        ),
        migrations.AddField(
            model_name='inscricao',
            name='kit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='evento.kit'),
        ),
    ]
