# Generated by Django 5.2.4 on 2025-07-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0007_alter_inscricao_participante_alter_inscricao_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='horarioIni',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
