# Generated by Django 5.2.4 on 2025-07-14 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0009_evento_imagem'),
        ('localidades', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='inscricao',
        ),
        migrations.AlterField(
            model_name='evento',
            name='localidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='localidades.localidade'),
        ),
        migrations.RemoveField(
            model_name='participante',
            name='localidade',
        ),
        migrations.RemoveField(
            model_name='organizador',
            name='participante',
        ),
        migrations.AlterField(
            model_name='evento',
            name='organizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='usuarios.organizador'),
        ),
        migrations.DeleteModel(
            name='inscricao',
        ),
        migrations.DeleteModel(
            name='pagamento',
        ),
        migrations.DeleteModel(
            name='localidade',
        ),
        migrations.DeleteModel(
            name='participante',
        ),
        migrations.DeleteModel(
            name='organizador',
        ),
    ]
