# Generated by Django 5.2.4 on 2025-07-14 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=15)),
                ('rua', models.CharField(max_length=100, null=True)),
                ('numero', models.CharField(max_length=10, null=True)),
                ('bairro', models.CharField(max_length=100, null=True)),
                ('localidade', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='localidades.localidade')),
            ],
        ),
        migrations.CreateModel(
            name='organizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('participante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizadores', to='usuarios.participante')),
            ],
        ),
    ]
